version: "3.9"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress
    restart: always


  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network
    depends_on:
      - mariadb
    restart: always


  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mdb_vol:/var/lib/mysql
    networks:
      - my_network
    restart: always


  website:
    container_name: website
    build: ./requirements/bonus/static_site
    ports:
      - "2002:2002"
    restart: always


networks:
  my_network:

volumes:
  wp_vol:
    name: wp_vol
    driver: local
    driver_opts:
      type: none
      device: /home/aelyakou/data/wp_vol
      o: bind
  mdb_vol:
    name: mdb_vol
    driver: local
    driver_opts:
      type: none
      device: /home/aelyakou/data/mdb_vol
      o: bind