version: "3.9"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress


  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network
    depends_on:
      - mariadb


  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mdb_vol:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  wp_vol:
    name: wp_vol
    driver: local
    driver_opts:
      type: none
      device: ./requirements/volumes/wp_vol
      o: bind
  mdb_vol:
    name: mdb_vol
    driver: local
    driver_opts:
      type: none
      device: ./requirements/volumes/mdb_vol
      o: bind