FROM debian:bullseye

RUN apt-get update && apt-get  install -y  mariadb-server

COPY ./tools/script.sh /

COPY tools/database.conf /etc/mysql/mariadb.conf.d/50-server.cnf

RUN chmod +x /script.sh

CMD ["./script.sh"]
