FROM debian:bullseye

RUN apt-get update -y && \
    apt-get install -y \
    nginx

COPY ./tools/index.html /var/www/html/index.html

COPY ./conf/nginx.conf /etc/nginx/sites-available/default

CMD ["nginx", "-g", "daemon off;"]