FROM debian:bullseye

RUN apt-get update -y && \
    apt-get install -y \
    nginx \
    openssl \
    vim \
    php7.4-fpm

RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -subj "/C=MO/ST=KHOURIBGUA/O=1337School/OU=42Network/CN=nginx" \
    -keyout /etc/nginx/ssl/sslkey.key \
    -out /etc/nginx/ssl/sslcrt.crt

COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]